name: Build & publish multiple docker images
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
        - dockerfile: ./cuda-libtorch/Dockerfile
          image: "cuda-libtorch"
           
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          dockerfile: ${{ matrix.dockerfile }}
          context: .
          image: ${{ matrix.image }}
          tags: ghcr.io/${{ matrix.image }}:latest
          push: true