name: Build & publish multiple docker images
on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
         - dockerfile: cuda-libtorch/Dockerfile
           image: "cuda-libtorch"
           
    steps:
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          dockerfile: ${{ matrix.dockerfile }}
          context: .
          image: : ${{ matrix.image }}
          tag: ghcr.io/${{ matrix.image }}:latest
          push: true